name: CI/CD Pipeline for Frontend

on:
  push:
    branches:
      - main  # 배포할 브랜치

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v3

      # Docker 설치 (필요한 경우에만)
      - name: Set up Docker
        run: |
          # Docker 설치 (GitHub Actions의 ubuntu-latest 환경에는 기본적으로 Docker가 설치되어 있음)
          if ! command -v docker &> /dev/null; then
            echo "Docker가 설치되어 있지 않습니다. 설치 중..."
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
          else
            echo "Docker가 이미 설치되어 있습니다."
          fi

      # Docker 이미지 빌드
      - name: Build Docker image for frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/stockey-react:latest .

      # Docker Hub에 푸시
      - name: Push Docker image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/stockey-react:latest

      # 서버에 배포 명령어 실행
      - name: Deploy to Server with Nginx
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu
            # 서버에서 Docker 이미지를 pull하고 실행
            docker pull ${{ secrets.DOCKER_USERNAME }}/stockey-react:latest
            
            # 기존에 실행 중인 컨테이너가 있으면 중지하고 제거
            docker stop stockey-react || true
            docker rm stockey-react || true

            # 새로운 컨테이너 실행 (Nginx와 연결)
            docker run -d --name stockey-react --network app-network -e VITE_SERVER_HOST=${{ secrets.EXPRESS_CONTAINER }} -p 80:80 ${{ secrets.DOCKER_USERNAME }}/stockey-react:latest